const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const state = { settings: null, user: null, results: [], galleryPage: 1, storages: [], authMode: 'login' };
const MIME_TYPES = [['image/jpeg','JPG'],['image/png','PNG'],['image/gif','GIF'],['image/webp','WebP']];

async function api(path, options = {}) {
  const headers = new Headers(options.headers || {});
  headers.set('X-Congyu-Request', '1');
  if (options.body && !(options.body instanceof FormData) && typeof options.body !== 'string') {
    headers.set('Content-Type', 'application/json'); options.body = JSON.stringify(options.body);
  }
  const response = await fetch(path, { credentials: 'same-origin', ...options, headers });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `请求失败 (${response.status})`);
  return data;
}

function toast(message, error = false) {
  const el = document.createElement('div'); el.className = `toast${error ? ' error' : ''}`; el.textContent = message;
  $('#toasts').append(el); setTimeout(() => el.remove(), 3600);
}
function formatBytes(value) { if (!value) return '0 B'; const u=['B','KB','MB','GB','TB']; const i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),u.length-1); return `${(value/1024**i).toFixed(i?1:0)} ${u[i]}`; }
function formatDate(value) { return new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value.replace(' ', 'T') + (value.includes('Z')?'':'Z'))); }
function setText(selector, text) { const el=$(selector); if(el)el.textContent=text; }
function button(text, cls='button ghost', action) { const b=document.createElement('button');b.type='button';b.className=cls;b.textContent=text;if(action)b.addEventListener('click',action);return b; }
async function copy(text, label='内容') { try { await navigator.clipboard.writeText(text); toast(`${label}已复制`); } catch { const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();document.execCommand('copy');area.remove();toast(`${label}已复制`); } }

function applySettings(settings) {
  state.settings = settings; document.title = settings.site_name; setText('#siteName', settings.site_name);
  document.documentElement.style.setProperty('--accent', settings.theme_color);
  const rgb = settings.theme_color.match(/[a-f\d]{2}/gi)?.map(v => parseInt(v,16)) || [59,130,246];
  document.documentElement.style.setProperty('--accent-rgb', rgb.join(','));
  const bg=$('#background'); bg.style.backgroundImage=settings.background_url?`url("${settings.background_url.replace(/["\\]/g,'')}")`:'none';bg.style.backgroundPosition=settings.background_position;bg.style.setProperty('--bg-opacity',settings.background_opacity/100);
  $('#gallerySection').hidden=!settings.gallery_enabled;
  const policy=state.user?state.user:{max_file_size:settings.guest_max_file_size,allowed_types:settings.guest_allowed_types};
  const labels=MIME_TYPES.filter(([m])=>policy.allowed_types.includes(m)).map(([,n])=>n).join(' / ');
  setText('#policyText',`${labels} · 单张不超过 ${formatBytes(policy.max_file_size)} · 最多 20 张`);
  $('#fileInput').accept=policy.allowed_types;
}
function applyUser(user) {
  state.user=user; $('#myImagesButton').hidden=!user;$('#adminButton').hidden=!user?.is_admin;
  $('#accountButton').textContent=user?user.username:'登录';
  if(state.settings)applySettings(state.settings);
}

async function init() {
  const data=await api('/api/bootstrap');applyUser(data.user);applySettings(data.settings);
  bindEvents(); if(data.settings.gallery_enabled)await loadGallery(true);
}

function bindEvents() {
  $('#themeButton').addEventListener('click',()=>{const root=document.documentElement;const dark=root.dataset.theme==='dark'||(!root.dataset.theme&&matchMedia('(prefers-color-scheme:dark)').matches);root.dataset.theme=dark?'light':'dark';localStorage.setItem('congyu-theme',root.dataset.theme);});
  const saved=localStorage.getItem('congyu-theme');if(saved)document.documentElement.dataset.theme=saved;
  $$('.upload-tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.upload-tab').forEach(t=>{t.classList.toggle('active',t===tab);t.setAttribute('aria-selected',String(t===tab))});$('#localPanel').hidden=tab.dataset.tab!=='local';$('#remotePanel').hidden=tab.dataset.tab!=='remote';}));
  const drop=$('#dropzone'), input=$('#fileInput');drop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}});input.addEventListener('change',()=>uploadFiles([...input.files]));
  ['dragenter','dragover'].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>uploadFiles([...e.dataTransfer.files].filter(f=>f.type.startsWith('image/'))));
  document.addEventListener('paste',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;const files=[...e.clipboardData.files].filter(f=>f.type.startsWith('image/'));if(files.length){e.preventDefault();uploadFiles(files)}});
  $('#remoteForm').addEventListener('submit',uploadRemote);$('#copyAllButton').addEventListener('click',()=>copy(state.results.map(x=>x.markdown).join('\n'),'Markdown'));
  $('#refreshGallery').addEventListener('click',()=>loadGallery(true));$('#loadMore').addEventListener('click',()=>loadGallery(false));
  $('#accountButton').addEventListener('click',()=>state.user?showAccountMenu():openAuth('login'));$('#authSwitch').addEventListener('click',()=>openAuth(state.authMode==='login'?'register':'login'));$('#authForm').addEventListener('submit',submitAuth);
  $('#myImagesButton').addEventListener('click',openLibrary);$('#adminButton').addEventListener('click',openAdmin);
  $$('.admin-tab').forEach(tab=>tab.addEventListener('click',()=>switchAdmin(tab.dataset.adminTab)));$('#settingsForm').addEventListener('submit',saveSettings);$('#settingsForm [name=background_opacity]').addEventListener('input',e=>setText('#opacityOutput',`${e.target.value}%`));
  $('#addStorageButton').addEventListener('click',()=>openStorage());$('#storageForm [name=type]').addEventListener('change',e=>renderStorageFields(e.target.value,{}));$('#storageForm').addEventListener('submit',saveStorage);
}

function showAccountMenu(){if(confirm(`当前登录：${state.user.username}\n\n确定要退出登录吗？`))api('/api/auth/logout',{method:'POST'}).then(()=>{applyUser(null);toast('已退出登录');loadGallery(true)}).catch(e=>toast(e.message,true));}
function openAuth(mode){state.authMode=mode;const register=mode==='register';setText('#authTitle',register?'注册账户':'登录');setText('#authSubmit',register?'注册并登录':'登录');setText('#authSwitch',register?'已有账户？返回登录':'没有账户？立即注册');$('#authSwitch').hidden=!register&&!state.settings.registration_enabled;$('#authPassword').autocomplete=register?'new-password':'current-password';$('#authDialog').showModal();}
async function submitAuth(e){e.preventDefault();try{const data=await api(`/api/auth/${state.authMode}`,{method:'POST',body:{username:$('#authUsername').value,password:$('#authPassword').value}});applyUser(data.user);$('#authDialog').close();toast(state.authMode==='login'?'登录成功':'注册成功');}catch(err){toast(err.message,true)}}

function queueItem(file){const el=document.createElement('div');el.className='queue-item';const name=document.createElement('span');name.textContent=file.name;const status=document.createElement('span');status.className='status';status.textContent='等待上传';const progress=document.createElement('div');progress.className='progress';progress.append(document.createElement('span'));el.append(name,status,progress);$('#queue').append(el);return{el,status,bar:progress.firstChild};}
async function uploadFiles(files){if(!files.length)return;if(files.length>20){toast('每次最多上传 20 张图片',true);files=files.slice(0,20)}const completed=[];await Promise.all(files.map(file=>new Promise(resolve=>{const q=queueItem(file);const form=new FormData();form.append('files',file);form.append('private',String($('#privateToggle').checked));const xhr=new XMLHttpRequest();xhr.open('POST','/api/upload');xhr.setRequestHeader('X-Congyu-Request','1');xhr.upload.onprogress=e=>{if(e.lengthComputable){q.bar.style.width=`${Math.round(e.loaded/e.total*90)}%`;q.status.textContent=`${Math.round(e.loaded/e.total*100)}%`}};xhr.onload=()=>{let data={};try{data=JSON.parse(xhr.responseText)}catch{}if(xhr.status>=200&&xhr.status<300&&data.images?.length){q.el.classList.add('done');q.status.textContent='完成';completed.push(...data.images);addResults(data.images)}else{q.el.classList.add('error');q.status.textContent=data.error||data.failures?.[0]?.error||'失败'}resolve()};xhr.onerror=()=>{q.el.classList.add('error');q.status.textContent='网络错误';resolve()};xhr.send(form)})));if(completed.length){await copy(completed.map(x=>x.markdown).join('\n'),'Markdown 链接');if(state.settings.gallery_enabled&&!$('#privateToggle').checked)loadGallery(true)}setTimeout(()=>{$$('#queue .done').forEach(x=>x.remove())},2500)}
async function uploadRemote(e){e.preventDefault();const submit=$('#remoteForm button');submit.disabled=true;submit.textContent='上传中…';try{const data=await api('/api/upload/url',{method:'POST',body:{url:$('#remoteURL').value,private:$('#privateToggle').checked}});addResults(data.images);await copy(data.images[0].markdown,'Markdown 链接');$('#remoteURL').value='';if(state.settings.gallery_enabled&&!$('#privateToggle').checked)loadGallery(true)}catch(err){toast(err.message,true)}finally{submit.disabled=false;submit.textContent='获取并上传'}}

function addResults(images){state.results.unshift(...images);$('#resultsSection').hidden=false;for(const item of [...images].reverse()){const card=document.createElement('article');card.className='result-card';const img=document.createElement('img');img.src=item.url;img.alt=item.original_name;img.loading='lazy';const info=document.createElement('div');info.className='result-info';const strong=document.createElement('strong');strong.textContent=item.original_name;const meta=document.createElement('span');meta.textContent=`${item.width} × ${item.height} · ${formatBytes(item.size)}${item.is_private?' · 隐私':''}`;info.append(strong,meta);const actions=document.createElement('div');actions.className='copy-actions';actions.append(button('外链','button ghost',()=>copy(item.url,'外链')),button('Markdown','button primary',()=>copy(item.markdown,'Markdown')));card.append(img,info,actions);$('#resultList').prepend(card)}}

async function loadGallery(reset){try{if(reset){state.galleryPage=1;$('#gallery').replaceChildren();}const data=await api(`/api/images?page=${state.galleryPage}`);if(reset&&!data.images.length){const empty=document.createElement('div');empty.className='empty-state';empty.textContent='还没有公开图片';$('#gallery').append(empty)}else data.images.forEach(renderGallery);$('#loadMore').hidden=!data.has_more;if(data.has_more)state.galleryPage++;}catch(err){toast(err.message,true)}}
function renderGallery(item){const card=document.createElement('article');card.className='gallery-card';const link=document.createElement('a');link.href=item.url;link.target='_blank';link.rel='noopener';const img=document.createElement('img');img.src=item.url;img.alt=item.original_name;img.width=item.width;img.height=item.height;img.loading='lazy';const meta=document.createElement('div');meta.className='gallery-meta';meta.textContent=`${item.username||'游客'} · ${formatDate(item.created_at)}`;link.append(img,meta);card.append(link);$('#gallery').append(card)}

async function openLibrary(){try{const data=await api('/api/images?scope=mine&page=1');const grid=$('#libraryGrid');grid.replaceChildren();if(!data.images.length){const e=document.createElement('div');e.className='empty-state';e.textContent='你还没有上传图片';grid.append(e)}data.images.forEach(item=>{const card=document.createElement('article');card.className='library-card';const img=document.createElement('img');img.src=item.url;img.alt=item.original_name;img.loading='lazy';const body=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('small'),actions=document.createElement('div');name.textContent=item.original_name;meta.textContent=`${formatBytes(item.size)}${item.is_private?' · 隐私':''}`;actions.className='library-actions';actions.append(button('复制','button ghost',()=>copy(item.markdown,'Markdown')),button('删除','button ghost danger',async()=>{if(!confirm('确定删除这张图片吗？此操作无法撤销。'))return;try{await api(`/api/images/${item.id}`,{method:'DELETE'});card.remove();toast('图片已删除')}catch(e){toast(e.message,true)}}));body.append(name,meta,actions);card.append(img,body);grid.append(card)});$('#libraryDialog').showModal()}catch(err){toast(err.message,true)}}

async function openAdmin(){try{await Promise.all([loadStats(),loadSettingsForm(),loadUsers(),loadStorages()]);switchAdmin('overview');$('#adminDialog').showModal()}catch(err){toast(err.message,true)}}
function switchAdmin(name){$$('.admin-tab').forEach(x=>x.classList.toggle('active',x.dataset.adminTab===name));$$('.admin-pane').forEach(x=>x.hidden=x.id!==`admin-${name}`)}
async function loadStats(){const data=await api('/api/admin/stats');const grid=$('#statsGrid');grid.replaceChildren();[['用户总数',data.users],['图片总数',data.images],['图片占用',formatBytes(data.bytes)]].forEach(([label,value])=>{const card=document.createElement('div');card.className='stat-card';const l=document.createElement('span'),v=document.createElement('strong');l.textContent=label;v.textContent=value;card.append(l,v);grid.append(card)});renderStorageStats(data.storages)}
function renderStorageStats(items){const wrap=$('#storageStats');wrap.replaceChildren();items.forEach(s=>{const el=document.createElement('div');el.className='storage-stat';const head=document.createElement('div');head.className='storage-stat-head';const title=document.createElement('strong'),usage=document.createElement('small');title.textContent=`${s.name} · ${s.type.toUpperCase()}`;usage.textContent=s.total_bytes?`${formatBytes(s.used_bytes)} / ${formatBytes(s.total_bytes)}`:`已用 ${formatBytes(s.used_bytes)} · 总容量未知`;head.append(title,usage);const meter=document.createElement('div');meter.className='meter';const fill=document.createElement('span');fill.style.width=s.total_bytes?`${Math.min(100,s.used_bytes/s.total_bytes*100)}%`:'0';meter.append(fill);el.append(head,meter);wrap.append(el)})}

async function loadSettingsForm(){const s=await api('/api/admin/settings');const f=$('#settingsForm');for(const key of ['site_name','site_domain','background_url','background_opacity','background_position','theme_color','webp_quality','guest_expiry_hours'])f.elements[key].value=s[key];f.elements.guest_max_file_size_mb.value=(s.guest_max_file_size/1048576).toFixed(2);for(const key of ['registration_enabled','guest_upload_enabled','gallery_enabled'])f.elements[key].checked=s[key];setText('#opacityOutput',`${s.background_opacity}%`);renderTypeChecks($('#guestTypeChecks'),s.guest_allowed_types,'guest_type')}
function renderTypeChecks(container,value,prefix){container.replaceChildren();MIME_TYPES.forEach(([mime,label])=>{const wrap=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=mime;input.name=prefix;input.checked=value.includes(mime);wrap.append(input,document.createTextNode(` ${label}`));container.append(wrap)})}
async function saveSettings(e){e.preventDefault();const f=e.currentTarget;const types=$$('input[name=guest_type]:checked',f).map(x=>x.value).join(',');const body={site_name:f.elements.site_name.value.trim(),site_domain:f.elements.site_domain.value.trim(),background_url:f.elements.background_url.value.trim(),background_opacity:+f.elements.background_opacity.value,background_position:f.elements.background_position.value,registration_enabled:f.elements.registration_enabled.checked,guest_upload_enabled:f.elements.guest_upload_enabled.checked,guest_allowed_types:types,guest_max_file_size:Math.round(+f.elements.guest_max_file_size_mb.value*1048576),guest_expiry_hours:+f.elements.guest_expiry_hours.value,gallery_enabled:f.elements.gallery_enabled.checked,theme_color:f.elements.theme_color.value,webp_quality:+f.elements.webp_quality.value};try{const saved=await api('/api/admin/settings',{method:'PUT',body});applySettings(saved);toast('网站设置已保存')}catch(err){toast(err.message,true)}}

async function loadUsers(){const users=await api('/api/admin/users');const body=$('#usersBody');body.replaceChildren();users.forEach(u=>{const tr=document.createElement('tr');const name=document.createElement('td');name.textContent=u.username;const role=document.createElement('td'),admin=document.createElement('input');admin.type='checkbox';admin.className='inline-check';admin.checked=u.is_admin;role.append(admin);const fileTd=document.createElement('td'),file=document.createElement('input');file.type='number';file.min='.01';file.step='.01';file.value=(u.max_file_size/1048576).toFixed(2);fileTd.append(file);const quotaTd=document.createElement('td'),quota=document.createElement('input');quota.type='number';quota.min='0';quota.step='.1';quota.value=(u.quota_bytes/1073741824).toFixed(2);quotaTd.append(quota);const used=document.createElement('td');used.textContent=formatBytes(u.used_bytes);const typeTd=document.createElement('td'),select=document.createElement('select');[['常用格式','image/jpeg,image/png,image/webp'],['包含 GIF','image/jpeg,image/png,image/gif,image/webp'],['仅 JPG / PNG','image/jpeg,image/png']].forEach(([label,val])=>{const o=new Option(label,val);if(val===u.allowed_types)o.selected=true;select.add(o)});if(![...select.options].some(x=>x.selected)){select.add(new Option('自定义',u.allowed_types,true,true))}typeTd.append(select);const actions=document.createElement('td'),wrap=document.createElement('div');wrap.className='mini-actions';wrap.append(button('保存','button primary',async()=>{try{await api(`/api/admin/users/${u.id}`,{method:'PUT',body:{is_admin:admin.checked,max_file_size:Math.round(+file.value*1048576),quota_bytes:Math.round(+quota.value*1073741824),allowed_types:select.value}});toast('用户权限已更新')}catch(e){toast(e.message,true)}}),button('删除','button ghost danger',async()=>{if(!confirm(`确定删除用户 ${u.username} 吗？`))return;try{await api(`/api/admin/users/${u.id}`,{method:'DELETE'});tr.remove();toast('用户已删除')}catch(e){toast(e.message,true)}}));actions.append(wrap);tr.append(name,role,fileTd,quotaTd,used,typeTd,actions);body.append(tr)})}

async function loadStorages(){state.storages=await api('/api/admin/storages');const list=$('#storageList');list.replaceChildren();state.storages.forEach(s=>{const el=document.createElement('article');el.className='storage-item';const head=document.createElement('div');head.className='storage-item-head';const info=document.createElement('div'),name=document.createElement('strong'),tags=document.createElement('div');name.textContent=s.name;tags.className='tags';[s.type.toUpperCase(),s.is_default?'默认':null,!s.enabled?'已停用':null].filter(Boolean).forEach(v=>{const tag=document.createElement('span');tag.className='tag';tag.textContent=v;tags.append(tag)});info.append(name,tags);const actions=document.createElement('div');actions.className='storage-item-actions';actions.append(button('编辑','button ghost',()=>openStorage(s)));if(!s.is_default)actions.append(button('删除','button ghost danger',async()=>{if(!confirm(`确定删除存储 ${s.name} 吗？`))return;try{await api(`/api/admin/storages/${s.id}`,{method:'DELETE'});await loadStorages();toast('存储已删除')}catch(e){toast(e.message,true)}}));head.append(info,actions);const meta=document.createElement('small');meta.textContent=s.total_bytes?`已用 ${formatBytes(s.used_bytes)}，可用 ${formatBytes(s.free_bytes)}`:`已用 ${formatBytes(s.used_bytes)}，总容量未配置`;el.append(head,meta);list.append(el)})}
function storageConfig(s){try{return JSON.parse(s?.config_json||'{}')}catch{return{}}}
function openStorage(storage=null){const f=$('#storageForm');f.reset();f.elements.id.value=storage?.id||'';f.elements.name.value=storage?.name||'';f.elements.type.value=storage?.type||'s3';f.elements.type.disabled=!!storage;f.elements.is_default.checked=storage?.is_default||false;f.elements.enabled.checked=storage?.enabled??true;setText('#storageTitle',storage?'编辑存储':'添加存储');renderStorageFields(f.elements.type.value,storageConfig(storage));$('#storageDialog').showModal()}
function renderStorageFields(type,cfg){const root=$('#storageFields');root.replaceChildren();if(type==='local'){const note=document.createElement('p');note.textContent='本机存储使用 DATA_DIR 下的 images 目录，无需额外配置。';note.style.color='var(--muted)';root.append(note);return}const fields=type==='s3'?[['endpoint','服务端点','s3.example.com'],['access_key','Access Key',''],['secret_key','Secret Key',''],['bucket','Bucket',''],['region','区域（可选）',''],['prefix','路径前缀（可选）',''],['capacity_gb','展示容量（GB）','0']]:[['url','WebDAV 地址','https://dav.example.com/images'],['username','用户名',''],['password','密码',''],['prefix','路径前缀（可选）',''],['capacity_gb','展示容量（GB）','0']];fields.forEach(([key,label,placeholder])=>{const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement('input');input.name=key;input.placeholder=placeholder;if(['secret_key','password'].includes(key))input.type='password';if(key==='capacity_gb'){input.type='number';input.min='0';input.step='.1';input.value=((cfg.capacity_bytes||0)/1073741824).toFixed(1)}else input.value=cfg[key]??'';wrap.append(input);root.append(wrap)});if(type==='s3'){const wrap=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.name='use_ssl';input.checked=cfg.use_ssl??true;wrap.className='check-row';wrap.append(input,document.createTextNode(' 使用 HTTPS'));root.append(wrap)}}
async function saveStorage(e){e.preventDefault();const f=e.currentTarget,type=f.elements.type.value,id=f.elements.id.value;let config;if(type==='local')config={};else if(type==='s3')config={endpoint:f.elements.endpoint.value.trim(),access_key:f.elements.access_key.value.trim(),secret_key:f.elements.secret_key.value,bucket:f.elements.bucket.value.trim(),region:f.elements.region.value.trim(),prefix:f.elements.prefix.value.trim(),use_ssl:f.elements.use_ssl.checked,capacity_bytes:Math.round(+f.elements.capacity_gb.value*1073741824)};else config={url:f.elements.url.value.trim(),username:f.elements.username.value.trim(),password:f.elements.password.value,prefix:f.elements.prefix.value.trim(),capacity_bytes:Math.round(+f.elements.capacity_gb.value*1073741824)};const body={name:f.elements.name.value.trim(),type,config_json:JSON.stringify(config),is_default:f.elements.is_default.checked,enabled:f.elements.enabled.checked};try{await api(id?`/api/admin/storages/${id}`:'/api/admin/storages',{method:id?'PUT':'POST',body});$('#storageDialog').close();await Promise.all([loadStorages(),loadStats()]);toast('存储设置已保存')}catch(err){toast(err.message,true)}}

init().catch(err=>{toast(err.message||'初始化失败',true);setText('#policyText','暂时无法连接服务器')});
